Revert one change that fails to compile in rake-compiler-dock
This is the compilation error I'm trying to fix:

```
ext/java/nokogiri/internals/NokogiriHelpers.java:744: error: cannot find symbol
    if (str.isEmpty()) { return str; } // no need to convert
           ^
  symbol:   method isEmpty()
  location: variable str of type CharSequence
```