Fix errors building Ruby 3.1 on windows
Drop testing system libraries for Ruby 3.1 because devkit is built
with a version of GCC that isn't compatible with modern msys2.

The error, on both syslib-enabled and -disabled Ruby 3.1 builds:

    pacman.exe -Sy --noconfirm --noprogressbar --needed --disable-download-timeout  mingw-w64-ucrt-x86_64-libxml2 mingw-w64-ucrt-x86_64-libxslt
    looking for conflicting packages...
    error: failed to prepare transaction (could not satisfy dependencies)
    :: installing mingw-w64-ucrt-x86_64-gcc-libs (15.2.0-8) breaks dependency 'mingw-w64-ucrt-x86_64-gcc-libs=14.2.0-3' required by mingw-w64-ucrt-x86_64-gcc
    Error: Command failed: pacman.exe -Sy --noconfirm --noprogressbar --needed --disable-download-timeout  mingw-w64-ucrt-x86_64-libxml2 mingw-w64-ucrt-x86_64-libxslt

(cherry picked from commit ae334cd25b02bbffec96d48f4973d356fd03e6af)