dev: update JavaExtensionTask source and target version to 1.7
because we were seeing these errors when building with 1.6:

> error: Source option 6 is no longer supported. Use 7 or later.
> error: Target option 6 is no longer supported. Use 7 or later.

I think this is because JRuby has been updated in the
rake-compiler-dock container since 1.0.0.